### ISSUE TITLE
Broken Commit

### ISSUE THREAD

**Issue by Jasperrr91** [intelligent-systems-course/planet-wars#1]
Hi there,

Commit: 2a02ac3cf6cb7e392aab61d0efbc6416a9e4aefe seems to break functionality.
`from api import Fleet, Planet, State` on line 10 in `_state.py` should be `from api import Fleet, Planet`.

**Comment by Jasperrr91** [comment]
Next issue is with the supplied play.py. For loading the bot, it uses this line of code:
`path = './{}/{}.py'.format(name, classname)`

But the bots are located in a subfolder `bots` and are named `name + Bot.py`, so it should be:
`path = './bots/{}/{}Bot.py'.format(name, classname)`

But the problems don't end there. The play script assumes the bots are placed in classes with the name of the bot as classname. But the example bots do not have this.

Adding the classname fixes this error but then the next one pops up:
``` File "/Users/admin/Documents/planet-wars/api/_state.py", line 216, in generate
    planets.append(Planet(0.0, 0.0, 10, 100))
TypeError: __init__() takes 4 positional arguments but 5 were given
```

`def __init__(x, y, size, id):`
=>
`def __init__(self, x, y, size, id):`

Then we get:
```garrisons[random.randint(1, 100)]
IndexError: list index out of range
```

Caused by `garrisons[random.randint(1, 100)]` being executed on the empty (`garrisons = []`) list of garrisons..

**Comment by pbloem** [comment]
Hi Jasper,

Thanks for the early bughunting. Unfortunately, the code currently comitted is quite a way behind the local version. I don't want to commit the things that the students have to fill in themselves (ie. working minimax agents and such). Expect a working codebase tomorrow or the day after.

**Comment by Jasperrr91** [comment]
Hi Peter,

I already thought so, I'll just wait for the working codebase then! Thanks,
