### ISSUE TITLE
train-ml-bot.py doesn't have a movements limit

### ISSUE THREAD

**Issue by CorralPeltzer** [intelligent-systems-course/planet-wars#5]
Is this intentional? If the performance of a bot is measured with a limit of 100 movements per game, I think the model created would be better with this limit.

**Comment by BlackNovaTech** [comment]
This is part of the rewrite, which will be online in a few hours after I verify it won't fuck everything up. 
Look out for nova-train.py!

**Comment by pbloem** [comment]
I agree that the training script should have a movement limit. Remember, however, that the script is just a simple example to get you started. You're free to change it how you like. If you think there's a better way to train a bot, implement it, and test the two versions against each other.
