### ISSUE TITLE
Ship generation not fair

### ISSUE THREAD

**Issue by ThomasPf** [intelligent-systems-course/planet-wars#8]
`             if self.__turn % planet.turns_per_ship() == 0 \
`
On line 188 of __state.py is not fair. Ship generation rate should be based on turns of ownership. Otherwise it would be better to attack a planet with a known spawn moment coming up compared to a planet that will take some more time. Because the spawn time for a short period will be a lot less then the actual spawn time (say 1 instead of 17 turns).

Thomas

**Comment by BlackNovaTech** [comment]
I do not see why this behavior is unfair nor unintended.

**Comment by ThomasPf** [comment]
because by rules of the game it doesn't spawn when the owner of the planet is neutral (or 0). So why has the spawn already started though the owner was at the time still neutral?

biem

**Comment by BlackNovaTech** [comment]
So how does this make the generation unfair? Targeting planets that are about to build a ship could be considered tactics.

**Comment by ThomasPf** [comment]
oke, *seems unfair
